name: release

on:
  release:
    types:
      - created

jobs:
  setup:
    name: Setup the ENV
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Xcaddy
      run: go get github.com/caddyserver/xcaddy/cmd/xcaddy@latest

  build:
    name: Build the binary
    needs: setup
    steps:
    - name: Build
      run: xcaddy build --with github.com/golevi/cache-handler

  upload:
    name: Upload the binary
    needs: build
    steps:
    - name: upload binary artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: release/